name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build and push bank-webhook image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: ./apps/bank-webhook
    #     file: ./apps/bank-webhook/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank-webhook:latest

    - name: Build and push merchant-app image
      uses: docker/build-push-action@v3
      with:
        context: ./apps/merchant-app
        file: ./apps/merchant-app/Dockerfile
        push: true
        tags: disha968/firstapp/merchant-app:latest

    - name: Build and push user-app image
      uses: docker/build-push-action@v3
      with:
        context: ./apps/user-app
        file: ./apps/user-app/Dockerfile
        push: true
        tags: disha968/firstapp/user-app:latest
