name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run Start
        run: npm run start
=======
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Start
        run: npm run start

      # - name: Run Lint
      #   run: npm run lint

>>>>>>> l
      # - name: Run Prettier
      #   run: npm run format
